name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/country-table:latest

  deploy-heroku:
    runs-on: ubuntu-latest
    needs: publish-docker-hub
    steps:
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Push iamge to Heroku Container Registry
        run: |
          heroku container:push web \
            --app ${{ secrets.HEROKU_APP_NAME }} \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/country-table:latest

      - name: Release image to Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
